import Image from "next/image";
import { Inter } from "next/font/google";
import Head from "next/head";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Yariga</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Link href="/">Home</Link>
        <Link href="/property">Property Page</Link>
        <Link
          href={{
            pathname: "property",
            query: {
              slug: "city-land",
            },
          }}
        >
          Property Page
        </Link>
      </header>
      <main>
        <h1>Home Page</h1>
      </main>
    </>
  );
}
